default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: scofflaw_development

test:
  <<: *default
  database: scofflaw_test

# production:
#   <<: *default
#   database: scofflaw_production
#   username: scofflaw
#   password: <%= ENV['SCOFFLAW_DATABASE_PASSWORD'] %>
