default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mix-list_development

test:
  <<: *default
  database: mix-list_test

# production:
#   <<: *default
#   database: mix-list_production
#   username: mix-list
#   password: <%= ENV['MIX-LIST_DATABASE_PASSWORD'] %>
